# Generated by Django 5.1.6 on 2025-02-24 09:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('aguardando_inicio', 'Aguardando Início'), ('em_andamento', 'Em Andamento'), ('documentos_pendentes', 'Documentos Pendentes'), ('documentos_invalidos', 'Documentos Inválidos'), ('concluido', 'Concluído')], default='aguardando_inicio', max_length=50)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('mensagem_enviada', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Candidato',
                'verbose_name_plural': 'Candidatos',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('rg', 'RG'), ('cpf', 'CPF'), ('cnh', 'CNH'), ('ctps', 'Carteira de Trabalho'), ('comprovante_residencia', 'Comprovante de Residência'), ('titulo_eleitor', 'Título de Eleitor'), ('outros', 'Outros')], max_length=50)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='documentos/')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('recebido', 'Recebido'), ('invalido', 'Inválido'), ('validado', 'Validado')], default='pendente', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('data_envio', models.DateTimeField(blank=True, null=True)),
                ('data_validacao', models.DateTimeField(blank=True, null=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='rh.candidato')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
        ),
    ]
