# Generated by Django 5.1.6 on 2025-03-12 13:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0006_alter_candidato_email_alter_documento_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='RegistroTempo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('cadastro', 'Cadastro do Candidato'), ('mensagem_enviada', 'Mensagem Enviada'), ('documento_solicitado', 'Documento Solicitado'), ('documento_recebido', 'Documento Recebido'), ('documento_validado', 'Documento Validado'), ('documento_invalidado', 'Documento Invalidado'), ('processo_concluido', 'Processo Concluído')], max_length=50)),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('status_anterior', models.CharField(blank=True, max_length=50, null=True)),
                ('status_novo', models.CharField(blank=True, max_length=50, null=True)),
                ('tempo_desde_evento_anterior', models.DurationField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_tempo', to='rh.candidato')),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registros_tempo', to='rh.documento')),
            ],
            options={
                'verbose_name': 'Registro de Tempo',
                'verbose_name_plural': 'Registros de Tempo',
                'ordering': ['-data_hora'],
            },
        ),
    ]
