# Generated by Django 5.1.6 on 2025-05-05 14:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0008_setor_candidato_criado_por_perfilusuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentacaoPessoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emissao', models.DateField(default=django.utils.timezone.now)),
                ('ocorrencia', models.CharField(choices=[('admissao_aumento', 'ADMISSÃO POR AUMENTO DE QUADRO'), ('admissao_substituicao', 'ADMISSÃO POR SUBSTITUIÇÃO'), ('desligamento', 'DESLIGAMENTO'), ('promocao', 'PROMOÇÃO / ENQUADRAMENTO'), ('transferencia', 'TRANSFERÊNCIA')], max_length=50)),
                ('nome_candidato', models.CharField(max_length=200)),
                ('email_candidato', models.EmailField(max_length=254)),
                ('telefone_candidato', models.CharField(max_length=20)),
                ('cargo_proposto', models.CharField(max_length=100)),
                ('area_proposta', models.CharField(max_length=100)),
                ('centro_custo_proposto', models.CharField(max_length=50)),
                ('salario_proposto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salario_por_hora', models.BooleanField(default=False)),
                ('data_admissao', models.DateField(blank=True, null=True)),
                ('nome_colaborador_substituido', models.CharField(blank=True, max_length=200, null=True)),
                ('registro_substituido', models.CharField(blank=True, max_length=50, null=True)),
                ('cargo_atual', models.CharField(blank=True, max_length=100, null=True)),
                ('area_atual', models.CharField(blank=True, max_length=100, null=True)),
                ('centro_custo_atual', models.CharField(blank=True, max_length=50, null=True)),
                ('salario_atual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ultimo_dia_trabalho', models.DateField(blank=True, null=True)),
                ('motivo_desligamento', models.CharField(blank=True, max_length=100, null=True)),
                ('data_ultimo_reajuste', models.DateField(blank=True, null=True)),
                ('percentual_reajuste', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('registro_admissao', models.CharField(blank=True, max_length=50, null=True)),
                ('visto_data_admissao', models.DateField(blank=True, null=True)),
                ('horario', models.CharField(blank=True, max_length=50, null=True)),
                ('idade', models.IntegerField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1, null=True)),
                ('estado_civil', models.CharField(blank=True, choices=[('solteiro', 'Solteiro(a)'), ('casado', 'Casado(a)'), ('divorciado', 'Divorciado(a)'), ('viuvo', 'Viúvo(a)'), ('uniao_estavel', 'União Estável')], max_length=20, null=True)),
                ('escolaridade', models.CharField(blank=True, choices=[('fundamental_incompleto', 'Fundamental Incompleto'), ('fundamental_completo', 'Fundamental Completo'), ('medio_incompleto', 'Médio Incompleto'), ('medio_completo', 'Médio Completo'), ('superior_incompleto', 'Superior Incompleto'), ('superior_completo', 'Superior Completo'), ('pos_graduacao', 'Pós-Graduação'), ('mestrado', 'Mestrado'), ('doutorado', 'Doutorado')], max_length=30, null=True)),
                ('experiencia', models.TextField(blank=True, null=True)),
                ('outros_requisitos', models.TextField(blank=True, null=True)),
                ('codigo_cargo', models.CharField(blank=True, max_length=50, null=True)),
                ('grupo_faixa', models.CharField(blank=True, max_length=50, null=True)),
                ('confidencial', models.BooleanField(default=False)),
                ('previsao_orcamentaria', models.BooleanField(default=False)),
                ('observacoes_recrutamento', models.TextField(blank=True, null=True)),
                ('data_assinatura_coordenacao', models.DateField(blank=True, null=True)),
                ('data_assinatura_gerencia', models.DateField(blank=True, null=True)),
                ('data_assinatura_diretoria', models.DateField(blank=True, null=True)),
                ('data_assinatura_rh', models.DateField(blank=True, null=True)),
                ('data_fechamento_vaga', models.DateField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_criadas', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimentação de Pessoal',
                'verbose_name_plural': 'Movimentações de Pessoal',
            },
        ),
    ]
