# Generated by Django 5.1.6 on 2025-05-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0011_movimentacaopessoal_area_proposta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.CharField(choices=[('rg', 'RG'), ('cpf', 'CPF'), ('cnh', 'CNH'), ('ctps', 'Carteira de Trabalho'), ('comprovante_residencia', 'Comprovante de Residência'), ('titulo_eleitor', 'Título de Eleitor'), ('foto_rosto', 'Foto do Rosto'), ('outros', 'Outros')], max_length=50),
        ),
    ]
