# Generated by Django 5.1.6 on 2025-05-20 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0013_tipodocumento_alter_documento_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipodocumento',
            name='nome_exibicao',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
