# Generated by Django 5.1.6 on 2025-07-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0017_tipodocumento_obrigatorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='data_ultima_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
