# Generated by Django 5.1.6 on 2025-07-28 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0018_documento_data_ultima_atualizacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='data_ultima_atualizacao',
        ),
    ]
