# Generated by Django 5.1.6 on 2025-08-06 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0019_remove_documento_data_ultima_atualizacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidato',
            options={'ordering': ['-data_cadastro'], 'verbose_name': 'Candidato', 'verbose_name_plural': 'Candidatos'},
        ),
    ]
