# Generated by Django 5.1.6 on 2025-08-27 18:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0023_delete_configuracaocobranca_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoCobranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='Automação Ativa')),
                ('dias_semana', models.JSONField(default=list, help_text='Lista dos dias da semana para envio (0=Segunda, 1=Terça, etc.)', verbose_name='Dias da Semana')),
                ('horarios', models.JSONField(default=list, help_text='Lista de horários no formato HH:MM', verbose_name='Horários de Disparo')),
                ('mensagem_template', models.TextField(default='Olá {nome}, você ainda possui documentos pendentes: {documentos}. Por favor, envie-os o mais breve possível.', help_text='Use {nome} para o nome do candidato e {documentos} para a lista de documentos', verbose_name='Template da Mensagem')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de Cobrança',
                'verbose_name_plural': 'Configurações de Cobrança',
            },
        ),
        migrations.CreateModel(
            name='ControleCobrancaCandidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cobranca_pausada', models.BooleanField(default=False, verbose_name='Cobrança Pausada')),
                ('data_pausa', models.DateTimeField(blank=True, null=True)),
                ('motivo_pausa', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('candidato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='controle_cobranca', to='rh.candidato')),
                ('pausado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cobranças_pausadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Controle de Cobrança do Candidato',
                'verbose_name_plural': 'Controles de Cobrança dos Candidatos',
            },
        ),
        migrations.CreateModel(
            name='HistoricoCobranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentos_cobrados', models.JSONField(help_text='Lista dos tipos de documentos que foram cobrados', verbose_name='Documentos Cobrados')),
                ('mensagem_enviada', models.TextField(verbose_name='Mensagem Enviada')),
                ('data_envio', models.DateTimeField(default=django.utils.timezone.now)),
                ('sucesso', models.BooleanField(default=True)),
                ('erro', models.TextField(blank=True, null=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_cobranças', to='rh.candidato')),
            ],
            options={
                'verbose_name': 'Histórico de Cobrança',
                'verbose_name_plural': 'Histórico de Cobranças',
                'ordering': ['-data_envio'],
            },
        ),
    ]
