# Generated by Django 5.1.6 on 2025-09-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0024_configuracaocobranca_controlecobrancacandidato_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('recebido', 'Recebido'), ('invalido', 'Inválido'), ('validado', 'Validado'), ('nao_possui', 'Não Possui')], default='pendente', max_length=20),
        ),
    ]
