# Generated by Django 5.1.6 on 2025-09-05 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0025_alter_documento_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrotempo',
            name='tipo_evento',
            field=models.CharField(choices=[('cadastro', 'Cadastro do Candidato'), ('mensagem_enviada', 'Mensagem Enviada'), ('documento_solicitado', 'Documento Solicitado'), ('documento_recebido', 'Documento Recebido'), ('documento_validado', 'Documento Validado'), ('documento_invalidado', 'Documento Invalidado'), ('processo_concluido', 'Processo Concluído'), ('candidato_status_alterado', 'Status do Candidato Alterado'), ('documento_removido_substituido', 'Documento Removido/Substituído'), ('documento_nao_possui', 'Documento Não Possui')], max_length=50),
        ),
    ]
