# Generated by Django 5.1.6 on 2025-09-08 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0026_alter_registrotempo_tipo_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('aguardando_inicio', 'Aguardando Início'), ('em_andamento', 'Em Andamento'), ('documentos_pendentes', 'Documentos Pendentes'), ('documentos_invalidos', 'Documentos Inválidos'), ('concluido', 'Concluído'), ('rejeitado', 'Rejeitado')], default='ativo', max_length=50),
        ),
    ]
