# Generated by Django 5.1.6 on 2025-09-24 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0029_alter_avaliacaoperiodoexperiencia_data_avaliacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaoperiodoexperiencia',
            name='aceita_opinioes_divergentes',
            field=models.IntegerField(choices=[(1, 'Sempre'), (2, 'Frequentemente'), (3, 'Raramente'), (4, 'Nunca')], null=True),
        ),
        migrations.AlterField(
            model_name='avaliacaoperiodoexperiencia',
            name='aceita_ordens_gestor',
            field=models.IntegerField(choices=[(1, 'Sempre'), (2, 'Frequentemente'), (3, 'Raramente'), (4, 'Nunca')], null=True),
        ),
        migrations.AlterField(
            model_name='avaliacaoperiodoexperiencia',
            name='adapta_novas_situacoes_clientes',
            field=models.IntegerField(choices=[(1, 'Sempre'), (2, 'Frequentemente'), (3, 'Raramente'), (4, 'Nunca')], null=True),
        ),
        migrations.AlterField(
            model_name='avaliacaoperiodoexperiencia',
            name='administra_tempo',
            field=models.IntegerField(choices=[(1, 'Sempre'), (2, 'Frequentemente'), (3, 'Raramente'), (4, 'Nunca')], null=True),
        ),
        migrations.AlterField(
            model_name='avaliacaoperiodoexperiencia',
            name='apresenta_iniciativa',
            field=models.IntegerField(choices=[(1, 'Sempre'), (2, 'Frequentemente'), (3, 'Raramente'), (4, 'Nunca')], null=True),
        ),
        migrations.AlterField(
            model_name='avaliacaoperiodoexperiencia',
            name='aptidao_lideranca',
            field=models.IntegerField(choices=[(1, 'Sempre'), (2, 'Frequentemente'), (3, 'Raramente'), (4, 'Nunca')], null=True),
        ),
        migrations.AlterField(
            model_name='avaliacaoperiodoexperiencia',
            name='assiduo',
            field=models.IntegerField(choices=[(1, 'Sempre'), (2, 'Frequentemente'), (3, 'Raramente'), (4, 'Nunca')], null=True),
        ),
        migrations.AlterField(
            model_name='avaliacaoperiodoexperiencia',
            name='autoconfiante',
            field=models.IntegerField(choices=[(1, 'Sempre'), (2, 'Frequentemente'), (3, 'Raramente'), (4, 'Nunca')], null=True),
        ),
        migrations.AlterField(
            model_name='avaliacaoperiodoexperiencia',
            name='colabora_membros_empresa',
            field=models.IntegerField(choices=[(1, 'Sempre'), (2, 'Frequentemente'), (3, 'Raramente'), (4, 'Nunca')], null=True),
        ),
        migrations.AlterField(
            model_name='avaliacaoperiodoexperiencia',
            name='comportamento_etico',
            field=models.IntegerField(choices=[(1, 'Sempre'), (2, 'Frequentemente'), (3, 'Raramente'), (4, 'Nunca')], null=True),
        ),
        migrations.AlterField(
            model_name='avaliacaoperiodoexperiencia',
            name='comunica_claro_coerente',
            field=models.IntegerField(choices=[(1, 'Sempre'), (2, 'Frequentemente'), (3, 'Raramente'), (4, 'Nunca')], null=True),
        ),
        migrations.AlterField(
            model_name='avaliacaoperiodoexperiencia',
            name='desiste_facil',
            field=models.IntegerField(choices=[(1, 'Sempre'), (2, 'Frequentemente'), (3, 'Raramente'), (4, 'Nunca')], null=True),
        ),
        migrations.AlterField(
            model_name='avaliacaoperiodoexperiencia',
            name='empenho_resultados_grupo',
            field=models.IntegerField(choices=[(1, 'Sempre'), (2, 'Frequentemente'), (3, 'Raramente'), (4, 'Nunca')], null=True),
        ),
        migrations.AlterField(
            model_name='avaliacaoperiodoexperiencia',
            name='expor_necessidades_perguntas',
            field=models.IntegerField(choices=[(1, 'Sempre'), (2, 'Frequentemente'), (3, 'Raramente'), (4, 'Nunca')], null=True),
        ),
        migrations.AlterField(
            model_name='avaliacaoperiodoexperiencia',
            name='interage_bem_colegas',
            field=models.IntegerField(choices=[(1, 'Sempre'), (2, 'Frequentemente'), (3, 'Raramente'), (4, 'Nunca')], null=True),
        ),
        migrations.AlterField(
            model_name='avaliacaoperiodoexperiencia',
            name='organizado_atividades',
            field=models.IntegerField(choices=[(1, 'Sempre'), (2, 'Frequentemente'), (3, 'Raramente'), (4, 'Nunca')], null=True),
        ),
        migrations.AlterField(
            model_name='avaliacaoperiodoexperiencia',
            name='pronto_para_colaborar',
            field=models.IntegerField(choices=[(1, 'Sempre'), (2, 'Frequentemente'), (3, 'Raramente'), (4, 'Nunca')], null=True),
        ),
        migrations.AlterField(
            model_name='avaliacaoperiodoexperiencia',
            name='reduz_despesas_desperdicios',
            field=models.IntegerField(choices=[(1, 'Sempre'), (2, 'Frequentemente'), (3, 'Raramente'), (4, 'Nunca')], null=True),
        ),
        migrations.AlterField(
            model_name='avaliacaoperiodoexperiencia',
            name='relutante_decisoes_grupo',
            field=models.IntegerField(choices=[(1, 'Sempre'), (2, 'Frequentemente'), (3, 'Raramente'), (4, 'Nunca')], null=True),
        ),
        migrations.AlterField(
            model_name='avaliacaoperiodoexperiencia',
            name='resultados_esperados',
            field=models.IntegerField(choices=[(1, 'Sempre'), (2, 'Frequentemente'), (3, 'Raramente'), (4, 'Nunca')], null=True),
        ),
        migrations.AlterField(
            model_name='avaliacaoperiodoexperiencia',
            name='talento_para_funcao',
            field=models.IntegerField(choices=[(1, 'Sempre'), (2, 'Frequentemente'), (3, 'Raramente'), (4, 'Nunca')], null=True),
        ),
    ]
