# Generated by Django 5.1.6 on 2025-09-24 19:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0030_alter_avaliacaoperiodoexperiencia_aceita_opinioes_divergentes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaoperiodoexperiencia',
            name='aprova_demite',
            field=models.IntegerField(choices=[(1, 'Aprovar'), (2, 'Demitir')], null=True),
        ),
        migrations.AlterField(
            model_name='avaliacaoperiodoexperiencia',
            name='data_avaliacao',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacaoperiodoexperiencia',
            name='respondido',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
