# Generated by Django 5.1.6 on 2025-02-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0005_candidato_ultima_tentativa_mensagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.CharField(choices=[('rg', 'RG'), ('cpf', 'CPF'), ('cnh', 'CNH'), ('ctps', 'Carteira de Trabalho'), ('comprovante_residencia', 'Comprovante de Residência'), ('titulo_eleitor', 'Título de Eleitor'), ('foto_rosto', 'Foto do Rosto'), ('outros', 'Outros')], max_length=50),
        ),
    ]
