# Generated by Django 5.1.6 on 2025-05-05 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0009_movimentacaopessoal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimentacaopessoal',
            name='area_proposta',
        ),
        migrations.RemoveField(
            model_name='movimentacaopessoal',
            name='cargo_proposto',
        ),
        migrations.RemoveField(
            model_name='movimentacaopessoal',
            name='centro_custo_proposto',
        ),
        migrations.RemoveField(
            model_name='movimentacaopessoal',
            name='data_admissao',
        ),
        migrations.RemoveField(
            model_name='movimentacaopessoal',
            name='email_candidato',
        ),
        migrations.RemoveField(
            model_name='movimentacaopessoal',
            name='salario_por_hora',
        ),
        migrations.RemoveField(
            model_name='movimentacaopessoal',
            name='salario_proposto',
        ),
        migrations.RemoveField(
            model_name='movimentacaopessoal',
            name='telefone_candidato',
        ),
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.CharField(choices=[('rg', 'RG'), ('cpf', 'CPF'), ('cnh', 'Carteira de Trabalho'), ('ctps', 'CNH'), ('comprovante_residencia', 'Comprovante de Residência'), ('titulo_eleitor', 'Título de Eleitor'), ('foto_rosto', 'Foto do Rosto'), ('outros', 'Outros')], max_length=50),
        ),
        migrations.AlterField(
            model_name='movimentacaopessoal',
            name='nome_candidato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes', to='rh.candidato'),
        ),
    ]
