# Generated by Django 5.1.6 on 2025-05-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0010_remove_movimentacaopessoal_area_proposta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaopessoal',
            name='area_proposta',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movimentacaopessoal',
            name='cargo_proposto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movimentacaopessoal',
            name='centro_custo_proposto',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='movimentacaopessoal',
            name='data_admissao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimentacaopessoal',
            name='salario_por_hora',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movimentacaopessoal',
            name='salario_proposto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
