# Generated by Django 5.1.6 on 2025-05-26 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0014_tipodocumento_nome_exibicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='tipo_contratacao',
            field=models.CharField(choices=[('clt', 'CLT'), ('pj', 'PJ')], default='clt', max_length=3, verbose_name='Tipo de Contratação'),
        ),
        migrations.AddField(
            model_name='tipodocumento',
            name='tipo_contratacao',
            field=models.CharField(choices=[('clt', 'CLT'), ('pj', 'PJ'), ('ambos', 'Ambos')], default='ambos', max_length=5, verbose_name='Tipo de Contratação'),
        ),
    ]
