# Generated by Django 5.1.6 on 2025-07-24 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0015_candidato_tipo_contratacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrotempo',
            name='tipo_evento',
            field=models.CharField(choices=[('cadastro', 'Cadastro do Candidato'), ('mensagem_enviada', 'Mensagem Enviada'), ('documento_solicitado', 'Documento Solicitado'), ('documento_recebido', 'Documento Recebido'), ('documento_validado', 'Documento Validado'), ('documento_invalidado', 'Documento Invalidado'), ('processo_concluido', 'Processo Concluído'), ('candidato_status_alterado', 'Status do Candidato Alterado'), ('documento_removido_substituido', 'Documento Removido/Substituído')], max_length=50),
        ),
    ]
