# Generated by Django 5.1.6 on 2025-07-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0016_alter_registrotempo_tipo_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipodocumento',
            name='obrigatorio',
            field=models.BooleanField(default=True, verbose_name='Obrigatório'),
        ),
    ]
