# Generated by Django 5.1.6 on 2025-08-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0020_alter_candidato_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='tentativas_revalidacao',
            field=models.IntegerField(default=0, help_text='Número de tentativas automáticas de revalidação realizadas pela IA', verbose_name='Tentativas de Revalidação'),
        ),
    ]
