# Generated by Django 5.1.6 on 2025-08-27 17:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0021_documento_tentativas_revalidacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoCobranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, help_text='Se marcado, a automação de cobrança funcionará conforme configurado', verbose_name='Automação Ativa')),
                ('dias_semana', models.JSONField(default=list, help_text='Lista dos dias da semana para envio (0=Segunda, 1=Terça, etc.)', verbose_name='Dias da Semana')),
                ('horarios_disparo', models.JSONField(default=dict, help_text='Dicionário com horários para cada dia da semana', verbose_name='Horários de Disparo')),
                ('validar_antes_envio', models.BooleanField(default=True, help_text='Se marcado, validará todos os documentos antes de enviar cobranças', verbose_name='Validar Documentos Antes do Envio')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de Cobrança',
                'verbose_name_plural': 'Configurações de Cobrança',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoCobrancaCandidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cobranca_pausada', models.BooleanField(default=False, help_text='Se marcado, este candidato não receberá cobranças automáticas', verbose_name='Cobrança Pausada')),
                ('data_pausa', models.DateTimeField(blank=True, null=True, verbose_name='Data da Pausa')),
                ('observacoes', models.TextField(blank=True, help_text='Motivo da pausa ou outras observações', verbose_name='Observações')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('candidato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_cobranca', to='rh.candidato')),
                ('pausado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Pausado Por')),
            ],
            options={
                'verbose_name': 'Configuração de Cobrança do Candidato',
                'verbose_name_plural': 'Configurações de Cobrança dos Candidatos',
            },
        ),
        migrations.CreateModel(
            name='HistoricoCobranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentos_cobrados', models.JSONField(help_text='Lista dos tipos de documentos que foram cobrados', verbose_name='Documentos Cobrados')),
                ('mensagem_enviada', models.TextField(verbose_name='Mensagem Enviada')),
                ('data_envio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data do Envio')),
                ('sucesso', models.BooleanField(default=True, verbose_name='Envio com Sucesso')),
                ('erro', models.TextField(blank=True, help_text='Detalhes do erro caso o envio tenha falhado', verbose_name='Erro')),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_cobrancas', to='rh.candidato')),
            ],
            options={
                'verbose_name': 'Histórico de Cobrança',
                'verbose_name_plural': 'Histórico de Cobranças',
                'ordering': ['-data_envio'],
            },
        ),
    ]
