# Generated by Django 5.1.6 on 2025-08-27 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0022_configuracaocobranca_configuracaocobrancacandidato_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfiguracaoCobranca',
        ),
        migrations.RemoveField(
            model_name='historicocobranca',
            name='candidato',
        ),
        migrations.DeleteModel(
            name='ConfiguracaoCobrancaCandidato',
        ),
        migrations.DeleteModel(
            name='HistoricoCobranca',
        ),
    ]
