# Generated by Django 5.1.6 on 2025-09-24 19:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0027_alter_candidato_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoPeriodoExperiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeira_segunda_avaliacao', models.IntegerField(choices=[(1, 'Primeira'), (2, 'Segunda')])),
                ('data_avaliacao', models.DateField(default=datetime.date(2025, 9, 24))),
                ('data_termino_experiencia', models.DateField()),
                ('gestor_avaliador', models.CharField(max_length=100)),
                ('colaborador', models.CharField(max_length=100)),
                ('data_admissao', models.DateField()),
                ('cargo', models.CharField(max_length=100)),
                ('respondido', models.BooleanField(default=False)),
                ('token', models.CharField(help_text='Token único para identificar a pesquisa no email', max_length=64, unique=True)),
                ('apresenta_iniciativa', models.IntegerField(choices=[(1, 'Sempre'), (2, 'Frequentemente'), (3, 'Raramente'), (4, 'Nunca')])),
                ('organizado_atividades', models.IntegerField(choices=[(1, 'Sempre'), (2, 'Frequentemente'), (3, 'Raramente'), (4, 'Nunca')])),
                ('adapta_novas_situacoes_clientes', models.IntegerField(choices=[(1, 'Sempre'), (2, 'Frequentemente'), (3, 'Raramente'), (4, 'Nunca')])),
                ('interage_bem_colegas', models.IntegerField(choices=[(1, 'Sempre'), (2, 'Frequentemente'), (3, 'Raramente'), (4, 'Nunca')])),
                ('aptidao_lideranca', models.IntegerField(choices=[(1, 'Sempre'), (2, 'Frequentemente'), (3, 'Raramente'), (4, 'Nunca')])),
                ('talento_para_funcao', models.IntegerField(choices=[(1, 'Sempre'), (2, 'Frequentemente'), (3, 'Raramente'), (4, 'Nunca')])),
                ('pronto_para_colaborar', models.IntegerField(choices=[(1, 'Sempre'), (2, 'Frequentemente'), (3, 'Raramente'), (4, 'Nunca')])),
                ('resultados_esperados', models.IntegerField(choices=[(1, 'Sempre'), (2, 'Frequentemente'), (3, 'Raramente'), (4, 'Nunca')])),
                ('colabora_membros_empresa', models.IntegerField(choices=[(1, 'Sempre'), (2, 'Frequentemente'), (3, 'Raramente'), (4, 'Nunca')])),
                ('comportamento_etico', models.IntegerField(choices=[(1, 'Sempre'), (2, 'Frequentemente'), (3, 'Raramente'), (4, 'Nunca')])),
                ('desiste_facil', models.IntegerField(choices=[(1, 'Sempre'), (2, 'Frequentemente'), (3, 'Raramente'), (4, 'Nunca')])),
                ('reduz_despesas_desperdicios', models.IntegerField(choices=[(1, 'Sempre'), (2, 'Frequentemente'), (3, 'Raramente'), (4, 'Nunca')])),
                ('comunica_claro_coerente', models.IntegerField(choices=[(1, 'Sempre'), (2, 'Frequentemente'), (3, 'Raramente'), (4, 'Nunca')])),
                ('administra_tempo', models.IntegerField(choices=[(1, 'Sempre'), (2, 'Frequentemente'), (3, 'Raramente'), (4, 'Nunca')])),
                ('autoconfiante', models.IntegerField(choices=[(1, 'Sempre'), (2, 'Frequentemente'), (3, 'Raramente'), (4, 'Nunca')])),
                ('empenho_resultados_grupo', models.IntegerField(choices=[(1, 'Sempre'), (2, 'Frequentemente'), (3, 'Raramente'), (4, 'Nunca')])),
                ('aceita_opinioes_divergentes', models.IntegerField(choices=[(1, 'Sempre'), (2, 'Frequentemente'), (3, 'Raramente'), (4, 'Nunca')])),
                ('relutante_decisoes_grupo', models.IntegerField(choices=[(1, 'Sempre'), (2, 'Frequentemente'), (3, 'Raramente'), (4, 'Nunca')])),
                ('expor_necessidades_perguntas', models.IntegerField(choices=[(1, 'Sempre'), (2, 'Frequentemente'), (3, 'Raramente'), (4, 'Nunca')])),
                ('assiduo', models.IntegerField(choices=[(1, 'Sempre'), (2, 'Frequentemente'), (3, 'Raramente'), (4, 'Nunca')])),
                ('aceita_ordens_gestor', models.IntegerField(choices=[(1, 'Sempre'), (2, 'Frequentemente'), (3, 'Raramente'), (4, 'Nunca')])),
                ('sugestao_critica_elogio', models.TextField(blank=True, null=True)),
                ('aprova_demite', models.IntegerField(choices=[(1, 'Aprovar'), (2, 'Demitir')])),
            ],
            options={
                'verbose_name': 'Avaliação de Experiência',
                'verbose_name_plural': 'Avaliações de Experiência',
            },
        ),
    ]
