# Generated by Django 5.1.6 on 2025-09-24 19:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0028_avaliacaoperiodoexperiencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaoperiodoexperiencia',
            name='data_avaliacao',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
